### ISSUE TITLE
[SDKAutorun] Tasks not remembered?

### ISSUE THREAD

**Issue by AzureShark** [apple1417/bl-sdk-mods#4]
**Mod Name**
SDKAutorun

**Full Mod List**
Installed mods:
Backpack Manager, Borderlands 2 Map Reloader, Drop Chance Multiplier, SDK Autorun, Sliding, Spawn Multiplier, BL2: Exodus, Be Gone Out of Bounds Loot, Borderlands Easy Read Only, Cross Class Skill Randomizer, Python Part Notifier (All requisites installed as well.)

Mods enabled:
SDK Autorun, Python Part Notifier

**Describe the bug**
Tasks do not save between game starts. (It also doesn't execute any of the tasks)
There is still a pycache folder created.

How to reproduce: 
Make task list (mine happened to have a console command as well as enable sdk mods)
Stop game and restart.
Hit T in the mod menu to edit tasks.

Images:
![Tasks before restart.](https://user-images.githubusercontent.com/20551944/102022653-3627ec80-3d56-11eb-8bf5-a25cf1235b0a.png)
![Tasks after restart.](https://user-images.githubusercontent.com/20551944/102022660-3f18be00-3d56-11eb-8f37-235ed63beb47.png)
![__pycache__ folder](https://user-images.githubusercontent.com/20551944/102022683-6b343f00-3d56-11eb-8f43-4caec39f391a.png)
![Files in __pycache__ folder](https://user-images.githubusercontent.com/20551944/102022685-6ff8f300-3d56-11eb-8341-7e21ec843bf2.png)

**Comment by apple1417** [comment]
Hmm this is odd, it looks like you've done everything right but I can't replicate it on my end. Are closing the game while the tasks menu is still open? If not, can you configure some tasks, exit to the main menu, then take a screenshot of console or send over the file `win32\pythonsdk.log`.

**Comment by AzureShark** [comment]
I'm not exiting while the menu is open, here is a image of the console as well as the log file.
![i5q4KDW 1](https://user-images.githubusercontent.com/20551944/102672949-4bd75080-4160-11eb-9658-5b36e50ef31d.png)

[python-sdk.log](https://github.com/apple1417/bl-sdk-mods/files/5718553/python-sdk.log)

**Comment by apple1417** [comment]
When you create tasks then exit out of the mod menu (but not the game), does it create a `settings.json` in the mod folder? There was an old sdk bug that caused that file to sometimes be deleted on launching the game. Best I can really suggest is re-install both the sdk and autorun.

**Comment by AzureShark** [comment]
There is a settings.json file, with these contents:
![cla1tJE 1](https://user-images.githubusercontent.com/20551944/102722760-4f3e1980-42d1-11eb-8543-bcf86df91ed9.png)

After reinstalling both Python SDK and SDK Autorun the settings folder has the same text (after it was made again) and the issue persists.
Edit for clarification: I fully deleted the old SDK Autorun folder before attempting to reinstall it.

**Comment by apple1417** [comment]
Well that at least proves it's not a permission issue. Does it edit that file when you create tasks and exit to the main menu (and not the game again)? Or does anything new get printed to console?

**Comment by AzureShark** [comment]
It does not edit the file when making tasks (and going to the main menu), and the console also says the same thing.

**Comment by apple1417** [comment]
The last thing I can really ask is can you try configure some tasks, and note down exactly what menus you go through in what order and how you navigate between them. A video would be best but a text description might also do.
