### ISSUE TITLE
Causes TPS to crash a lot

### ISSUE THREAD

**Issue by gitdrug** [apple1417/bl-sdk-mods#6]
Causes TPS to crash a lot
Mods;
AltUseVenders, Elums.

It just makes TPS crash and very unstable.

**Comment by apple1417** [comment]
Alt use itself should not be able to cause crashes, need a lot more info here, it obviously works for everyone else. Join the [modding support discord](https://discord.gg/bXeqV8Ef9R) for an faq and more detailed help.

**Comment by gitdrug** [comment]
It was windows not the mods This was fixed by me enabling compatibility mode
